# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gps_stable_gui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(610, 360)
        Dialog.setMaximumSize(QtCore.QSize(721, 484))
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 60, 251, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.head_gps_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.head_gps_layout.setObjectName("head_gps_layout")
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.head_gps_layout.addWidget(self.line, 0, 1, 1, 1)
        self.head_lon = QtWidgets.QLabel(self.gridLayoutWidget)
        self.head_lon.setText("")
        self.head_lon.setObjectName("head_lon")
        self.head_gps_layout.addWidget(self.head_lon, 1, 2, 1, 1)
        self.head_lat = QtWidgets.QLabel(self.gridLayoutWidget)
        self.head_lat.setText("")
        self.head_lat.setObjectName("head_lat")
        self.head_gps_layout.addWidget(self.head_lat, 0, 2, 1, 1)
        self.head_lon_title = QtWidgets.QLabel(self.gridLayoutWidget)
        self.head_lon_title.setObjectName("head_lon_title")
        self.head_gps_layout.addWidget(self.head_lon_title, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.head_lat_title = QtWidgets.QLabel(self.gridLayoutWidget)
        self.head_lat_title.setObjectName("head_lat_title")
        self.head_gps_layout.addWidget(self.head_lat_title, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.head_gps_layout.addWidget(self.line_2, 1, 1, 1, 1)
        self.tail_gps_title = QtWidgets.QLabel(Dialog)
        self.tail_gps_title.setGeometry(QtCore.QRect(140, 30, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.tail_gps_title.setFont(font)
        self.tail_gps_title.setTextFormat(QtCore.Qt.RichText)
        self.tail_gps_title.setObjectName("tail_gps_title")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(110, 50, 118, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.head_gps_title_2 = QtWidgets.QLabel(Dialog)
        self.head_gps_title_2.setGeometry(QtCore.QRect(140, 170, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.head_gps_title_2.setFont(font)
        self.head_gps_title_2.setTextFormat(QtCore.Qt.RichText)
        self.head_gps_title_2.setObjectName("head_gps_title_2")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(110, 190, 118, 3))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(50, 200, 251, 101))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.tail_gps_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.tail_gps_layout.setObjectName("tail_gps_layout")
        self.line_5 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.tail_gps_layout.addWidget(self.line_5, 0, 1, 1, 1)
        self.tail_lon = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.tail_lon.setText("")
        self.tail_lon.setObjectName("tail_lon")
        self.tail_gps_layout.addWidget(self.tail_lon, 1, 2, 1, 1)
        self.tail_lat = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.tail_lat.setText("")
        self.tail_lat.setObjectName("tail_lat")
        self.tail_gps_layout.addWidget(self.tail_lat, 0, 2, 1, 1)
        self.tail_lon_title = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.tail_lon_title.setObjectName("tail_lon_title")
        self.tail_gps_layout.addWidget(self.tail_lon_title, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.tail_lat_title = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.tail_lat_title.setObjectName("tail_lat_title")
        self.tail_gps_layout.addWidget(self.tail_lat_title, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.line_6 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.tail_gps_layout.addWidget(self.line_6, 1, 1, 1, 1)
        self.pot_angle_title = QtWidgets.QLabel(Dialog)
        self.pot_angle_title.setGeometry(QtCore.QRect(100, 320, 67, 17))
        self.pot_angle_title.setObjectName("pot_angle_title")
        self.line_7 = QtWidgets.QFrame(Dialog)
        self.line_7.setGeometry(QtCore.QRect(170, 310, 16, 41))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.pot_angle = QtWidgets.QLabel(Dialog)
        self.pot_angle.setGeometry(QtCore.QRect(200, 320, 67, 17))
        self.pot_angle.setText("")
        self.pot_angle.setObjectName("pot_angle")
        self.robot_heading_title = QtWidgets.QLabel(Dialog)
        self.robot_heading_title.setGeometry(QtCore.QRect(346, 30, 101, 20))
        self.robot_heading_title.setObjectName("robot_heading_title")
        self.line_8 = QtWidgets.QFrame(Dialog)
        self.line_8.setGeometry(QtCore.QRect(450, 20, 16, 51))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.robot_heading = QtWidgets.QLabel(Dialog)
        self.robot_heading.setGeometry(QtCore.QRect(480, 30, 67, 17))
        self.robot_heading.setText("")
        self.robot_heading.setObjectName("robot_heading")
        self.line_9 = QtWidgets.QFrame(Dialog)
        self.line_9.setGeometry(QtCore.QRect(450, 80, 16, 51))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.wheel_heading_title = QtWidgets.QLabel(Dialog)
        self.wheel_heading_title.setGeometry(QtCore.QRect(340, 90, 121, 20))
        self.wheel_heading_title.setObjectName("wheel_heading_title")
        self.wheel_heading = QtWidgets.QLabel(Dialog)
        self.wheel_heading.setGeometry(QtCore.QRect(480, 90, 67, 17))
        self.wheel_heading.setText("")
        self.wheel_heading.setObjectName("wheel_heading")
        self.line_10 = QtWidgets.QFrame(Dialog)
        self.line_10.setGeometry(QtCore.QRect(450, 140, 16, 51))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.steering_cmd_title = QtWidgets.QLabel(Dialog)
        self.steering_cmd_title.setGeometry(QtCore.QRect(346, 150, 101, 20))
        self.steering_cmd_title.setObjectName("steering_cmd_title")
        self.steering_cmd = QtWidgets.QLabel(Dialog)
        self.steering_cmd.setGeometry(QtCore.QRect(480, 150, 67, 17))
        self.steering_cmd.setText("")
        self.steering_cmd.setObjectName("steering_cmd")
        self.launch_button = QtWidgets.QPushButton(Dialog)
        self.launch_button.setGeometry(QtCore.QRect(400, 220, 111, 27))
        self.launch_button.setObjectName("launch_button")
        self.kill_button = QtWidgets.QPushButton(Dialog)
        self.kill_button.setGeometry(QtCore.QRect(400, 260, 111, 27))
        self.kill_button.setObjectName("kill_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.head_lon_title.setText(_translate("Dialog", "Longitude"))
        self.head_lat_title.setText(_translate("Dialog", "Lattitude"))
        self.tail_gps_title.setText(_translate("Dialog", "Head GPS"))
        self.head_gps_title_2.setText(_translate("Dialog", "Tail GPS"))
        self.tail_lon_title.setText(_translate("Dialog", "Longitude"))
        self.tail_lat_title.setText(_translate("Dialog", "Lattitude"))
        self.pot_angle_title.setText(_translate("Dialog", "Pot Angle"))
        self.robot_heading_title.setText(_translate("Dialog", "Robot Heading"))
        self.wheel_heading_title.setText(_translate("Dialog", "Wheel Heading"))
        self.steering_cmd_title.setText(_translate("Dialog", "Steering Cmd"))
        self.launch_button.setText(_translate("Dialog", "Launch"))
        self.kill_button.setText(_translate("Dialog", "Kill"))
